ALTER TABLE MOZO
ADD CONSTRAINT MOZO_PK PRIMARY KEY (id_mozo);

ALTER TABLE MESA
ADD CONSTRAINT MESA_PK PRIMARY KEY (id_mesa);

ALTER TABLE ASIGNACION_MOZO_MESA
ADD CONSTRAINT MOZO_MESA_PK PRIMARY KEY (MOZO_id_mozo,
MESA_id_mesa,fecha_desde);

ALTER TABLE SERVICIO_MESA
ADD CONSTRAINT SERVICIO_MESA_PK PRIMARY KEY (MENUS_id_menu,
A_MOZO_MESA_MOZO_id_mozo,A_MOZO_MESA_MESA_id_mesa,
A_MOZO_MESA_fecha_desde,fecha_servicio,
hora_servicio);

ALTER TABLE MENUS
ADD CONSTRAINT MENUS_PK PRIMARY KEY (id_menu);