ALTER TABLE ASIGNACION_MOZO_MESA
ADD CONSTRAINT MOZO_MESA_MOZO_FK FOREIGN KEY (MOZO_id_mozo)
REFERENCES MOZO(id_mozo);

ALTER TABLE ASIGNACION_MOZO_MESA
ADD CONSTRAINT MOZO_MESA_MESA_FK FOREIGN KEY (MESA_id_mesa)
REFERENCES MESA(id_mesa);

ALTER TABLE SERVICIO_MESA
ADD CONSTRAINT SERVICIO_MESA_MENUS_FK FOREIGN KEY (MENUS_id_menu)
REFERENCES MENUS(id_menu);

ALTER TABLE SERVICIO_MESA
ADD CONSTRAINT SERVICIO_MESA_ASIGNACION_MOZO_MESA_FK FOREIGN KEY (A_MOZO_MESA_MOZO_id_mozo,A_MOZO_MESA_MESA_id_mesa,A_MOZO_MESA_fecha_desde)
REFERENCES ASIGNACION_MOZO_MESA(MOZO_id_mozo,MESA_id_mesa,fecha_desde);