ALTER TABLE MOZO
DROP CONSTRAINT MOZO_PK;

ALTER TABLE MESA
DROP CONSTRAINT MESA_PK;

ALTER TABLE ASIGNACION_MOZO_MESA
DROP CONSTRAINT MOZO_MESA_PK;

ALTER TABLE SERVICIO_MESA
DROP CONSTRAINT SERVICIO_MESA_PK;

ALTER TABLE MENUS
DROP CONSTRAINT MENUS_PK;