ALTER TABLE ASIGNACION_MOZO_MESA
DROP CONSTRAINT MOZO_MESA_MOZO_FK;

ALTER TABLE ASIGNACION_MOZO_MESA
DROP CONSTRAINT MOZO_MESA_MESA_FK;

ALTER TABLE SERVICIO_MESA
DROP CONSTRAINT SERVICIO_MESA_MENUS_FK;

ALTER TABLE SERVICIO_MESA
DROP CONSTRAINT SERVICIO_MESA_ASIGNACION_MOZO_MESA_FK ;